# docker-compose.yml
version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1] 88.222.213.214"
    volumes:
      - ./profiles:/var/app/profiles
      - ./recordings:/var/app/recordings
